name: hello-world-pipeine
on: [ push ]
jobs:
  print-my-secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo $SECRET_IDENTITY
        env:
          $SECRE_IDENTITY: ${{secrets.SECRET_IDENTITY}}