name: hello-world-pipeine
on: [ push ]
jobs:
  print-my-secret:
    runs-on: ubuntu-latest
    steps:
      - env:
          SECRET_IDENTITY: ${{ secrets.SECRET_IDENTITY }}
        run: echo $SECRET_IDENTITY
