name: hello-world-pipeine
on: [ push ]
jobs:
  print-my-secret:
    runs-on: ubuntu-latest
    steps:
      - name: run $SECRET_IDENTITY
        shell: bash
        env:
          secret: ${{ secrets.SECRET_IDENTITY }}
        run: |
          echo "$secret"
