name: hello-world-pipeine
on: [ push ]
jobs:
  print-my-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo $SECRET_IDENTITY
        with:
          secret: ${{secrets.SECRET_IDENTITY}}
      - run: echo secret